server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;
    server_name _;

    # React client
    location / {
        try_files $uri /index.html;
    }

    # Proxy API requests to backend
    location /api/ {
        proxy_pass https://capstone-project-backend-4mpo.onrender.com/;
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
        
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
           
           # larger buffer cause of JWT
        proxy_buffer_size 16k;
        proxy_buffers 4 16k;
        proxy_busy_buffers_size 16k;
    }
    client_header_buffer_size 4k;
    large_client_header_buffers 4 16k;
}